blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://github.com/blazinginstruments/blazingkraft-issues/discussions/new?category=feature-requests
    about: Request new feature
  - name: Ask a question, give feedback, share your project
    url: https://github.com/blazinginstruments/blazingkraft-issues/discussions
    about: Connect with other community members with GitHub discussions
  - name: Get help on Discord
    url: https://discord.gg/TRnjvvZtWU
    about: Get help from the community on Discord